version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*database/sql.DB).Close
        - (*go.uber.org/zap.Logger).Sync
        - (*net/http.Response).Body.Close
